esphome:
  name: dedietrich
  friendly_name: DeDietrich
  includes:
    - dietrich_mcx.h

esp8266:
  board: huzzah

# Enable logging
logger:
#  baud_rate: 0
  hardware_uart: UART1

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dedietrich Fallback Hotspot"
    password: ""

captive_portal:
    
uart:
  id: uart_bus
  baud_rate: 9600
  tx_pin: GPIO01 # 01
  rx_pin: GPIO03 # 03
  stop_bits: 1

text_sensor:
  - platform: template
    id: kociol_status_txt
    name: "Kocioł Status"
  - platform: template
    id: kociol_zatrzymanie_txt
    name: "Kocioł kod zatrzymania"
  - platform: template
    id: kociol_blokada_txt
    name: "Kocioł kod blokady"

sensor:
  - platform: custom
    lambda: |-
      auto dietrich = new Dietrich(id(uart_bus));
      App.register_component(dietrich);
      return {dietrich->state_sensor, dietrich->lockout_sensor, dietrich->blocking_sensor, 
        dietrich->flow_temp_sensor, dietrich->return_temp_sensor, dietrich->outside_temp_sensor, dietrich->calorifier_temp_sensor, 
        dietrich->boiler_control_temp_sensor, dietrich->room_temp_sensor, dietrich->ch_setpoint_sensor, dietrich->dhw_setpoint_sensor, dietrich->room_temp_setpoint_sensor,
        dietrich->fan_speed_setpoint_sensor, dietrich->fan_speed_sensor,                  
        dietrich->ionisation_current_sensor, dietrich->internal_setpoint_sensor, dietrich->available_power_sensor, dietrich->pump_percentage_sensor,
        dietrich->desired_max_power_sensor, dietrich->actual_power_sensor,
        dietrich->demand_source_bit0_sensor, dietrich->demand_source_bit1_sensor, dietrich->demand_source_bit2_sensor, dietrich->demand_source_bit3_sensor,
        dietrich->demand_source_bit4_sensor, dietrich->demand_source_bit5_sensor, dietrich->demand_source_bit6_sensor, dietrich->demand_source_bit7_sensor,      
        dietrich->hours_run_pump_sensor, dietrich->hours_run_3way_sensor, dietrich->hours_run_ch_sensor, dietrich->hours_run_dhw_sensor,
        dietrich->power_supply_avail_hours_sensor, dietrich->pump_starts_sensor, dietrich->number_of3way_valve_cycles_sensor, dietrich->burner_start_dhw_sensor,
        dietrich->total_burner_start_sensor, dietrich->failed_burner_start_sensor, dietrich->number_flame_loss_sensor 
      };

    sensors:
    - id: kociol_status
      on_value:
        then:
          - lambda: |-
              if (id(kociol_status).state==0) {id(kociol_status_txt).publish_state("0:Czuwanie");} //0:Off-position, no heat demand 
              else if (id(kociol_status).state==1) {id(kociol_status_txt).publish_state("1:Wentylacja przed/po");} //1:Pre-vent./post-ventilation
              else if (id(kociol_status).state==2) {id(kociol_status_txt).publish_state("2:Zapłon");} //2:Ignition
              else if (id(kociol_status).state==3) {id(kociol_status_txt).publish_state("3:Ogrzewanie CO");} //Burning CH
              else if (id(kociol_status).state==4) {id(kociol_status_txt).publish_state("4:Ogrzewanie CWU");} //Burning DHW
              else if (id(kociol_status).state==5) {id(kociol_status_txt).publish_state("5:Zatrzymanie palnika");} //5:Anti hunting time CH"
              else if (id(kociol_status).state==6) {id(kociol_status_txt).publish_state("6:Czas pompy po CO");} //6:Post pump time CH 
              else if (id(kociol_status).state==7) {id(kociol_status_txt).publish_state("7:Czas pompy po CWU");} //7:Post pump time DHW
              else if (id(kociol_status).state==8) {id(kociol_status_txt).publish_state("8:Kontrolowane zatrzymanie");} //Controlled stop
              else if (id(kociol_status).state==9) {id(kociol_status_txt).publish_state("9:Wyłączenie");} //Blocking mode
              else if (id(kociol_status).state==10) {id(kociol_status_txt).publish_state("10:Cykl wentylacji");} //"10:Ventingcycle" 
              else if (id(kociol_status).state==11) {id(kociol_status_txt).publish_state("11:Wymuszony niski płomień z palnika");} //"11:Forced burner low flame"
              else if (id(kociol_status).state==12) {id(kociol_status_txt).publish_state("12:Wymusz wys płom CO");} //"12:Forced burner high CH" 
              else if (id(kociol_status).state==13) {id(kociol_status_txt).publish_state("13:Wymusz wys płom DHW");} //"13:Forced burner high DHW"
              else if (id(kociol_status).state==15) {id(kociol_status_txt).publish_state("15:Ręczne żądanie temp");} //"15:Manual heat demand"
              else 
                {id(kociol_status_txt).publish_state("999:Nieznany");}

    - id: kociol_zatrzymanie
      name: "Kocioł lockout"
      on_value: 
        then:
          - lambda: |-
              if (id(kociol_zatrzymanie).state==0) {id(kociol_zatrzymanie_txt).publish_state("E00: Błąd czujnika");} //E00: Sensor error
              else if (id(kociol_zatrzymanie).state==1) {id(kociol_zatrzymanie_txt).publish_state("E01: Przepływ &gt;Tmax.");} //E01: Flow &gt; Tmax.
              else if (id(kociol_zatrzymanie).state==2) {id(kociol_zatrzymanie_txt).publish_state("E02: Powrót &gt; Przepływ");} //E02: Return &gt; Flow
              else if (id(kociol_zatrzymanie).state==3) {id(kociol_zatrzymanie_txt).publish_state("E03: Błąd uziemienia");} //E03: Earthing fault
              else if (id(kociol_zatrzymanie).state==4) {id(kociol_zatrzymanie_txt).publish_state("E04: Brak płomienia");} //E04: No flame
              else if (id(kociol_zatrzymanie).state==5) {id(kociol_zatrzymanie_txt).publish_state("E05: Więcej niz 5 błędów rozruchu");} //E05: &gt;5 start failures
              else if (id(kociol_zatrzymanie).state==6) {id(kociol_zatrzymanie_txt).publish_state("E06: Symulacja płomieni");} //E06: Flame simulation"
              else if (id(kociol_zatrzymanie).state==7) {id(kociol_zatrzymanie_txt).publish_state("E07: Zbyt niskie ciśnienie wody");} //E07: Water pressure to low"
              else if (id(kociol_zatrzymanie).state==8) {id(kociol_zatrzymanie_txt).publish_state("E08: Błąd wentylatora");} //E08: Fan error"
              else if (id(kociol_zatrzymanie).state==9) {id(kociol_zatrzymanie_txt).publish_state("E09: Niskie ciśnienie hydrauliczne");} //E09: Low hydraulic pressure
              else if (id(kociol_zatrzymanie).state==10) {id(kociol_zatrzymanie_txt).publish_state("E10: Niewystarczające odpowietrzenie");} //E10: insufficient deairation
              else if (id(kociol_zatrzymanie).state==11) {id(kociol_zatrzymanie_txt).publish_state("E11: Temp skrzyni powietrzniej &gt; maks.");} //E11: Airbox temp. &gt; max.
              else if (id(kociol_zatrzymanie).state==12) {id(kociol_zatrzymanie_txt).publish_state("E12: Błąd kontroli HRU");} //E12: Error checking HRU
              else if (id(kociol_zatrzymanie).state==13) {id(kociol_zatrzymanie_txt).publish_state("E13: zapłon / fuse");} //E13: fuse
              else if (id(kociol_zatrzymanie).state==43) {id(kociol_zatrzymanie_txt).publish_state("E43: Granice parametrów");} //E43: Parameter bounds 
              else if (id(kociol_zatrzymanie).state==44) {id(kociol_zatrzymanie_txt).publish_state("E44: Suma kontrolna param");} // E44: Parameter checksum
              else if (id(kociol_zatrzymanie).state==45) {id(kociol_zatrzymanie_txt).publish_state("E45: Parametry domyślne");} //E45: Default parameters
              else if (id(kociol_zatrzymanie).state==46) {id(kociol_zatrzymanie_txt).publish_state("E46: błąd tabeli dF/dU");} // E46: dF/dU table error
              else if (id(kociol_zatrzymanie).state==255) {id(kociol_zatrzymanie_txt).publish_state("Wszystko OK");} // SNAFU
              else 
                {id(kociol_zatrzymanie_txt).publish_state("999:Nieznany kod zamykający");} // Unknown locking code
    
    - id: kociol_blokada
      name: "Kocioł blocking"
      on_value: 
        then:
          - lambda: |-
              if (id(kociol_blokada).state==40) {id(kociol_blokada_txt).publish_state("B40: Nieznane kody kotła");} //B40: Boiler codes unknown
              else if (id(kociol_blokada).state==80) {id(kociol_blokada_txt).publish_state("B80: wprowadzanie wyłączenia");} //B80: shut down input
              else if (id(kociol_blokada).state==81) {id(kociol_blokada_txt).publish_state("B81: Błąd kontroli HRU");} //B81: error checking HRU
              else if (id(kociol_blokada).state==82) {id(kociol_blokada_txt).publish_state("B82: Ogrz kotł prom sł, DHW wył");} //B82: Solar boiler warm, DHW off
              else if (id(kociol_blokada).state==83) {id(kociol_blokada_txt).publish_state("B83: Błąd czuj podgrzewacza");} //B83: Calorifier sensor error
              else if (id(kociol_blokada).state==90) {id(kociol_blokada_txt).publish_state("B90: wzrost temperatury");} //B90: temperaure increase
              else if (id(kociol_blokada).state==91) {id(kociol_blokada_txt).publish_state("B91: deltaT zbyt wysoka");} //B91: deltaT to big
              else if (id(kociol_blokada).state==92) {id(kociol_blokada_txt).publish_state("B92: niedostateczny przepływ");} //B92: insufficient flow
              else if (id(kociol_blokada).state==255) {id(kociol_blokada_txt).publish_state("Wszystko OK");} // SNAFU
              else 
                {id(kociol_blokada_txt).publish_state("999:Nieznany kod blokujący");} // Unknown blocking code
        
    - name: "Kocioł temp. przepływu"
      unit_of_measurement: °C
      accuracy_decimals: 2
    - name: "Kocioł temp. powrotu"
      unit_of_measurement: °C
      accuracy_decimals: 2
    - name: "Kocioł temp. zewnętrzna"
      unit_of_measurement: °C
      accuracy_decimals: 2
    - name: "Kocioł temp. podgrzewacza"
      unit_of_measurement: °C
      accuracy_decimals: 2
    - name: "Kocioł temp. kotła"
      unit_of_measurement: °C
      accuracy_decimals: 2
    - name: "Kocioł temp. pomieszczenia"
      unit_of_measurement: °C
      accuracy_decimals: 2
    - name: "Kocioł zadana temp. CO"
      unit_of_measurement: °C
      accuracy_decimals: 2
    - name: "Kocioł zadana temp. CWU"
      unit_of_measurement: °C
      accuracy_decimals: 2  
    - name: "Kocioł zadana temp. pomieszczenia"
      unit_of_measurement: °C
      accuracy_decimals: 2  
    - name: "Kocioł zadana prędkość wentylatora"
      unit_of_measurement: rpm
      accuracy_decimals: 2  
    
    - name: "Kocioł prędkość wentylatora"
      unit_of_measurement: rpm
      accuracy_decimals: 2  

    - name: "Kocioł prąd jonizacji"
      unit_of_measurement: "μA"
      accuracy_decimals: 1  
    - name: "Kocioł wewnętrzna wartość zadana"
      unit_of_measurement: "%"
      accuracy_decimals: 0  
    - name: "Kocioł dostępna moc"
      unit_of_measurement: "%"
      accuracy_decimals: 0  
    - name: "Kocioł procent pracy pompy"
      unit_of_measurement: "%"
      accuracy_decimals: 0  
    
    - name: "Kocioł oczekiwana moc maksymalna"
      unit_of_measurement: "%"
      accuracy_decimals: 0  
    - name: "Kocioł moc aktualna"
      unit_of_measurement: "%"
      accuracy_decimals: 0      
      
    - name: "Kocioł Podłączony kontroler modulujący"
    - name: "Kocioł Żądanie grzania z kontrolera modulującego"
    - name: "Kocioł Żądanie grzania z kontrolera wł/wył"
    - name: "Kocioł Zabezpieczenie przed zamarznięciem"        
    - name: "Kocioł CWU Eko"
    - name: "Kocioł CWU Blokada"
    - name: "Kocioł AntyLegionella"
    - name: "Kocioł Żądanie grzania CWU"

    - name: "Kocioł ilość godzin pracy pompy"
      unit_of_measurement: h
      accuracy_decimals: 0  
    - name: "Kocioł ilość godzin pracy zaworu trójdrożnego"
      unit_of_measurement: h
      accuracy_decimals: 0  
    - name: "Kocioł ilość godzin pracy"
      unit_of_measurement: h
      accuracy_decimals: 0  
    - name: "Kocioł ilość godzin pracy CWU"
      unit_of_measurement: h
      accuracy_decimals: 0  
    - name: "Kocioł ilość godzin zasilania"
      unit_of_measurement: h
      accuracy_decimals: 0  
      
    - name: "Kocioł ilość startów pompy"
      unit_of_measurement: il
      accuracy_decimals: 0
    - name: "Kocioł ilość trójdrożnych cykli zaworu"
      unit_of_measurement: il
      accuracy_decimals: 0
    - name: "Kocioł ilość startów CWU"
      unit_of_measurement: il
      accuracy_decimals: 0
    - name: "Kocioł ilość startów palnika"
      unit_of_measurement: il
      accuracy_decimals: 0
    - name: "Kocioł ilość nieudanych startów palnika"
      unit_of_measurement: il
      accuracy_decimals: 0
    - name: "Kocioł ilość awarii płomienia"
      unit_of_measurement: il
      accuracy_decimals: 0
          
  - platform: wifi_signal
    name: "Kocioł poziom sygnału WiFi"
    update_interval: 60s
    
  - platform: uptime
    name: "Kocioł Uptime"  
